sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t vpdocker15/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true vpdocker15/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "frontend"
  env: "frontend-env"
  bucket_name: "elasticbeanstalk-ap-south-1-211125668680"
  bucket_path: "frontend"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
